version: "3.7"

networks:
  agent_network:
    driver: overlay
    attachable: true

  traefik_network:
    driver: overlay
    external: true

volumes:
  portainer: {}

services:
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer:/data
    networks:
      - agent_network
      - traefik_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_network
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.middlewares.portainer-redirectscheme.redirectscheme.scheme=https

        - traefik.http.routers.portainer_insecure.entrypoints=web
        - traefik.http.routers.portainer_insecure.middlewares=portainer-redirectscheme
        - traefik.http.routers.portainer_insecure.rule=Host(`portainer.domain.com`)

        - traefik.http.routers.portainer_secured.tls=true
        - traefik.http.routers.portainer_secured.entrypoints=web-secure
        - traefik.http.routers.portainer_secured.rule=Host(`portainer.domain.com`)

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
