version: "3.7"

networks:
  agent_network:
    driver: overlay
    attachable: true

  traefik_network:
    driver: overlay
    external: true

volumes:
  db-data: {}

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agent_network
      - traefik_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_network
        - traefik.http.services.swarmpit.loadbalancer.server.port=8080
        - traefik.http.middlewares.swarmpit-redirectscheme.redirectscheme.scheme=https

        - traefik.http.routers.swarmpit_insecure.entrypoints=web
        - traefik.http.routers.swarmpit_insecure.middlewares=swarmpit-redirectscheme
        - traefik.http.routers.swarmpit_insecure.rule=Host(`swarmpit.domain.com`)

        - traefik.http.routers.swarmpit_secured.tls=true
        - traefik.http.routers.swarmpit_secured.entrypoints=web-secure
        - traefik.http.routers.swarmpit_secured.rule=Host(`swarmpit.domain.com`)

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
